spring.application.name=Cohort-The-Platform

###database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}
spring.jpa.database-platform=${DATABASE_DIALECT}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

###JWT
JWT_SECRET_KEY=${JWT_SECRET_KEY}

###LIQUIBASE
spring.liquibase.change-log=${LIQUIBASE_CHANGELOG}
spring.liquibase.contexts=dev

###SPRING-MAIL
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
logging.level.org.springframework.security=DEBUG

###AWS-S3
aws.s3.bucketName=your-bucket-name
aws.s3.accessKey=your-access-key
aws.s3.secretKey=your-secret-key