-- liquibase formatted sql

-- changeset Coditas-Admin:1782360035123-1
CREATE TABLE announcement
(
    announcement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id          BIGINT                                  NOT NULL,
    content           VARCHAR(255)                            NOT NULL,
    announcement_date date                                    NOT NULL,
    created_by        BIGINT                                  NOT NULL,
    CONSTRAINT pk_announcement PRIMARY KEY (announcement_id)
);

-- changeset Coditas-Admin:1782360035123-2
CREATE TABLE assignment
(
    assignment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id              BIGINT                                  NOT NULL,
    assignmnet_title       VARCHAR(255)                            NOT NULL,
    assignmnet_description VARCHAR(255)                            NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deadline_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    uploaded_by            BIGINT                                  NOT NULL,
    is_active              BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_assignment PRIMARY KEY (assignment_id)
);

-- changeset Coditas-Admin:1782360035123-3
CREATE TABLE cohort_user
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name   VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    joined_date date                                    NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    "is-active" BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_cohort_user PRIMARY KEY (user_id)
);

-- changeset Coditas-Admin:1782360035123-4
CREATE TABLE course
(
    course_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_name        VARCHAR(255)                            NOT NULL,
    course_description VARCHAR(255)                            NOT NULL,
    created_at         date                                    NOT NULL,
    "is-active"        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (course_id)
);

-- changeset Coditas-Admin:1782360035123-5
CREATE TABLE course_batch
(
    course_batch_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id        BIGINT                                  NOT NULL,
    enrollment_limit BIGINT                                  NOT NULL,
    instructor_id    BIGINT                                  NOT NULL,
    start_date       date                                    NOT NULL,
    end_date         date                                    NOT NULL,
    "is-active"      BOOLEAN                                 NOT NULL,
    created_at       date                                    NOT NULL,
    CONSTRAINT pk_course_batch PRIMARY KEY (course_batch_id)
);

-- changeset Coditas-Admin:1782360035123-6
CREATE TABLE course_material
(
    material_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_name VARCHAR(255)                            NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    file_name     VARCHAR(255)                            NOT NULL,
    file_key      VARCHAR(255)                            NOT NULL,
    upload_date   date                                    NOT NULL,
    uploaded_by   BIGINT                                  NOT NULL,
    CONSTRAINT pk_course_material PRIMARY KEY (material_id)
);

-- changeset Coditas-Admin:1782360035123-7
CREATE TABLE enrollment
(
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id      BIGINT                                  NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    enrolled_at   date                                    NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_enrollment PRIMARY KEY (enrollment_id)
);

-- changeset Coditas-Admin:1782360035123-8
CREATE TABLE refresh_token
(
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token            VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    blacklisted      BOOLEAN                                 NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (refresh_token_id)
);

-- changeset Coditas-Admin:1782360035123-9
CREATE TABLE submission
(
    submission_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_id     BIGINT                                  NOT NULL,
    student_id        BIGINT                                  NOT NULL,
    file_name         VARCHAR(255)                            NOT NULL,
    file_key          VARCHAR(255)                            NOT NULL,
    submitted_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    submission_status VARCHAR(255)                            NOT NULL,
    grade             VARCHAR(255),
    feedback          VARCHAR(255),
    graded_by         BIGINT,
    graded_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_submission PRIMARY KEY (submission_id)
);

-- changeset Coditas-Admin:1782360035123-10
ALTER TABLE cohort_user
    ADD CONSTRAINT uc_cohort_user_email UNIQUE (email);

-- changeset Coditas-Admin:1782360035123-11
ALTER TABLE course_batch
    ADD CONSTRAINT uc_course_batch_instructor UNIQUE (instructor_id);

-- changeset Coditas-Admin:1782360035123-12
ALTER TABLE submission
    ADD CONSTRAINT uc_submission_submitted_at UNIQUE (submitted_at);

-- changeset Coditas-Admin:1782360035123-13
ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_BATCH FOREIGN KEY (batch_id) REFERENCES course_batch (course_batch_id);

-- changeset Coditas-Admin:1782360035123-14
ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-15
ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782360035123-16
ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-17
ALTER TABLE course_batch
    ADD CONSTRAINT FK_COURSE_BATCH_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782360035123-18
ALTER TABLE course_batch
    ADD CONSTRAINT FK_COURSE_BATCH_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-19
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782360035123-20
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-21
ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_BATCH FOREIGN KEY (batch_id) REFERENCES course_batch (course_batch_id);

-- changeset Coditas-Admin:1782360035123-22
ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-23
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-24
ALTER TABLE submission
    ADD CONSTRAINT FK_SUBMISSION_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignment (assignment_id);

-- changeset Coditas-Admin:1782360035123-25
ALTER TABLE submission
    ADD CONSTRAINT FK_SUBMISSION_ON_GRADED_BY FOREIGN KEY (graded_by) REFERENCES cohort_user (user_id);

-- changeset Coditas-Admin:1782360035123-26
ALTER TABLE submission
    ADD CONSTRAINT FK_SUBMISSION_ON_STUDENT FOREIGN KEY (student_id) REFERENCES cohort_user (user_id);

