-- liquibase formatted sql

-- changeset Coditas-Admin:1782365397026-1
CREATE TABLE invitation
(
    invitation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name         VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    role              SMALLINT                                NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    unique_key        VARCHAR(255)                            NOT NULL,
    invitation_status VARCHAR(255)                            NOT NULL,
    inviter_id        BIGINT,
    CONSTRAINT pk_invitation PRIMARY KEY (invitation_id)
);

-- changeset Coditas-Admin:1782365397026-2
ALTER TABLE invitation
    ADD CONSTRAINT uc_invitation_unique_key UNIQUE (unique_key);

-- changeset Coditas-Admin:1782365397026-3
ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_INVITER FOREIGN KEY (inviter_id) REFERENCES cohort_user (user_id);

