-- liquibase formatted sql

-- changeset Coditas-Admin:1782310150816-1
CREATE TABLE announcement
(
    announcement_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id            BIGINT                                  NOT NULL,
    content              VARCHAR(255)                            NOT NULL,
    announcement_date    date                                    NOT NULL,
    announcement_made_by BIGINT                                  NOT NULL,
    CONSTRAINT pk_announcement PRIMARY KEY (announcement_id)
);

-- changeset Coditas-Admin:1782310150816-2
CREATE TABLE assignment
(
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    uploaded_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deadline_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    uploaded_by   BIGINT                                  NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_assignment PRIMARY KEY (assignment_id)
);

-- changeset Coditas-Admin:1782310150816-3
CREATE TABLE assignment_feedback
(
    feedback_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_id BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    feedback      VARCHAR(255)                            NOT NULL,
    course_id     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_assignment_feedback PRIMARY KEY (feedback_id)
);

-- changeset Coditas-Admin:1782310150816-4
CREATE TABLE course
(
    course_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_name      VARCHAR(255)                            NOT NULL,
    enrollment_limit BIGINT                                  NOT NULL,
    course_link      VARCHAR(255)                            NOT NULL,
    "is-active"      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (course_id)
);

-- changeset Coditas-Admin:1782310150816-5
CREATE TABLE course_batch
(
    course_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date      date                                    NOT NULL,
    end_date        date                                    NOT NULL,
    course_id       BIGINT                                  NOT NULL,
    instructor_id   BIGINT                                  NOT NULL,
    "is-active"     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_course_batch PRIMARY KEY (course_batch_id)
);

-- changeset Coditas-Admin:1782310150816-6
CREATE TABLE course_material
(
    material_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_name VARCHAR(255)                            NOT NULL,
    material_link VARCHAR(255)                            NOT NULL,
    upload_date   date                                    NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_course_material PRIMARY KEY (material_id)
);

-- changeset Coditas-Admin:1782310150816-7
CREATE TABLE refresh_token
(
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token            VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    blacklisted      BOOLEAN                                 NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (refresh_token_id)
);

-- changeset Coditas-Admin:1782310150816-8
CREATE TABLE student_assignment
(
    student_assignment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id             BIGINT                                  NOT NULL,
    assignment_id          BIGINT                                  NOT NULL,
    assignment_upload_link VARCHAR(255)                            NOT NULL,
    upload_date            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_student_assignment PRIMARY KEY (student_assignment_id)
);

-- changeset Coditas-Admin:1782310150816-9
CREATE TABLE student_course_enrollment
(
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_student_course_enrollment PRIMARY KEY (enrollment_id)
);

-- changeset Coditas-Admin:1782310150816-10
CREATE TABLE users
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name   VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    joined_date date                                    NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    "is-active" BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset Coditas-Admin:1782310150816-11
ALTER TABLE course_batch
    ADD CONSTRAINT uc_course_batch_instructor UNIQUE (instructor_id);

-- changeset Coditas-Admin:1782310150816-12
ALTER TABLE course
    ADD CONSTRAINT uc_course_course_link UNIQUE (course_link);

-- changeset Coditas-Admin:1782310150816-13
ALTER TABLE student_assignment
    ADD CONSTRAINT uc_student_assignment_upload_date UNIQUE (upload_date);

-- changeset Coditas-Admin:1782310150816-14
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Coditas-Admin:1782310150816-15
ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_ANNOUNCEMENT_MADE_BY FOREIGN KEY (announcement_made_by) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782310150816-16
ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782310150816-17
ALTER TABLE assignment_feedback
    ADD CONSTRAINT FK_ASSIGNMENT_FEEDBACK_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignment (assignment_id);

-- changeset Coditas-Admin:1782310150816-18
ALTER TABLE assignment_feedback
    ADD CONSTRAINT FK_ASSIGNMENT_FEEDBACK_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES assignment (assignment_id);

-- changeset Coditas-Admin:1782310150816-19
ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782310150816-20
ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782310150816-21
ALTER TABLE course_batch
    ADD CONSTRAINT FK_COURSE_BATCH_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782310150816-22
ALTER TABLE course_batch
    ADD CONSTRAINT FK_COURSE_BATCH_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782310150816-23
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782310150816-24
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782310150816-25
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782310150816-26
ALTER TABLE student_assignment
    ADD CONSTRAINT FK_STUDENT_ASSIGNMENT_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignment (assignment_id);

-- changeset Coditas-Admin:1782310150816-27
ALTER TABLE student_assignment
    ADD CONSTRAINT FK_STUDENT_ASSIGNMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES assignment (assignment_id);

-- changeset Coditas-Admin:1782310150816-28
ALTER TABLE student_course_enrollment
    ADD CONSTRAINT FK_STUDENT_COURSE_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (course_id);

-- changeset Coditas-Admin:1782310150816-29
ALTER TABLE student_course_enrollment
    ADD CONSTRAINT FK_STUDENT_COURSE_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (user_id);

