-- liquibase formatted sql

-- changeset Coditas-Admin:1782289528096-1
CREATE TABLE announcements
(
    announcement_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id            BIGINT                                  NOT NULL,
    content              VARCHAR(255)                            NOT NULL,
    announcement_date    date                                    NOT NULL,
    announcement_made_by BIGINT                                  NOT NULL,
    CONSTRAINT pk_announcements PRIMARY KEY (announcement_id)
);

-- changeset Coditas-Admin:1782289528096-2
CREATE TABLE assignment_feedback
(
    feedback_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_id BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    feedback      VARCHAR(255)                            NOT NULL,
    course_id     SMALLINT                                NOT NULL,
    CONSTRAINT pk_assignment_feedback PRIMARY KEY (feedback_id)
);

-- changeset Coditas-Admin:1782289528096-3
CREATE TABLE assignments
(
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    uploaded_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deadline_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    uploaded_by   BIGINT                                  NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_assignments PRIMARY KEY (assignment_id)
);

-- changeset Coditas-Admin:1782289528096-4
CREATE TABLE course_material
(
    material_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_name VARCHAR(255)                            NOT NULL,
    material_link VARCHAR(255)                            NOT NULL,
    upload_date   date                                    NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_course_material PRIMARY KEY (material_id)
);

-- changeset Coditas-Admin:1782289528096-5
CREATE TABLE courses
(
    course_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_name      VARCHAR(255)                            NOT NULL,
    upload_date      date                                    NOT NULL,
    enrollment_limit BIGINT                                  NOT NULL,
    instructor_id    BIGINT                                  NOT NULL,
    course_link      VARCHAR(255)                            NOT NULL,
    "is-active"      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (course_id)
);

-- changeset Coditas-Admin:1782289528096-6
CREATE TABLE student_assignment
(
    student_assignment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id             BIGINT                                  NOT NULL,
    assignment_id          BIGINT                                  NOT NULL,
    assignment_upload_link VARCHAR(255)                            NOT NULL,
    upload_date            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_student_assignment PRIMARY KEY (student_assignment_id)
);

-- changeset Coditas-Admin:1782289528096-7
CREATE TABLE student_course_enrollment
(
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_student_course_enrollment PRIMARY KEY (enrollment_id)
);

-- changeset Coditas-Admin:1782289528096-8
CREATE TABLE users
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name   VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    joined_date date                                    NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    "is-active" BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset Coditas-Admin:1782289528096-9
ALTER TABLE courses
    ADD CONSTRAINT uc_courses_course_link UNIQUE (course_link);

-- changeset Coditas-Admin:1782289528096-10
ALTER TABLE courses
    ADD CONSTRAINT uc_courses_instructor UNIQUE (instructor_id);

-- changeset Coditas-Admin:1782289528096-11
ALTER TABLE student_assignment
    ADD CONSTRAINT uc_student_assignment_upload_date UNIQUE (upload_date);

-- changeset Coditas-Admin:1782289528096-12
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Coditas-Admin:1782289528096-13
ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_ANNOUNCEMENT_MADE_BY FOREIGN KEY (announcement_made_by) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782289528096-14
ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (course_id);

-- changeset Coditas-Admin:1782289528096-15
ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (course_id);

-- changeset Coditas-Admin:1782289528096-16
ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782289528096-17
ALTER TABLE assignment_feedback
    ADD CONSTRAINT FK_ASSIGNMENT_FEEDBACK_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignments (assignment_id);

-- changeset Coditas-Admin:1782289528096-18
ALTER TABLE assignment_feedback
    ADD CONSTRAINT FK_ASSIGNMENT_FEEDBACK_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES assignments (assignment_id);

-- changeset Coditas-Admin:1782289528096-19
ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782289528096-20
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (course_id);

-- changeset Coditas-Admin:1782289528096-21
ALTER TABLE course_material
    ADD CONSTRAINT FK_COURSE_MATERIAL_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (user_id);

-- changeset Coditas-Admin:1782289528096-22
ALTER TABLE student_assignment
    ADD CONSTRAINT FK_STUDENT_ASSIGNMENT_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignments (assignment_id);

-- changeset Coditas-Admin:1782289528096-23
ALTER TABLE student_assignment
    ADD CONSTRAINT FK_STUDENT_ASSIGNMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES assignments (assignment_id);

-- changeset Coditas-Admin:1782289528096-24
ALTER TABLE student_course_enrollment
    ADD CONSTRAINT FK_STUDENT_COURSE_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (course_id);

-- changeset Coditas-Admin:1782289528096-25
ALTER TABLE student_course_enrollment
    ADD CONSTRAINT FK_STUDENT_COURSE_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (user_id);

